### ISSUE TITLE
add a users view for the details panel

### ISSUE THREAD

**Issue by michaelbrooks** [etcgroup/agave#27]
Should display a list of users sorted according to some criterion - number of tweets? number of mentions? number of retweets?

**Comment by mtork** [comment]
Hmmm good point. I will have to think more about this. Possibly number of mentions or retweets? The only reason I was thinking not number of tweets is potentially because of spam? Or just because people send a lot of tweets, doesn't mean they would be of interest. It would probably be easier to identify popular users with mentions or retweets. Possibly in the future display the number of mentions, tweets, and retweets and the user can sort them?

**Comment by michaelbrooks** [comment]
Agreed. Just pick one for now, whatever is easy and not unreasonable. John
started adding changeable sort parameters to queries.php, but I think I'll
need to redo a lot of how that class works tomorrow.

**Comment by michaelbrooks** [comment]
@mtork finished in 00e61670809cfa1ed666bd8248862727a6cdbf5c, 27c54a688653590a2532953af6070335b8fa9697, and 08c7e154e35f1980ab82daf12589fc80b2a4a282 mostly
